### ISSUE TITLE
add cache header to resources 

### ISSUE THREAD

**Issue by danduk82** [geoadmin/config-tileservergl#26]
add cache headers so that proxies and browsers react accordingly.

for index files, something like 5 minutes, for tiles 1 week to start.

**Comment by ltkum** [comment]
https://github.com/geoadmin/config-tileservergl/pull/27 

I'll modify the values before merging, those were the values from what we discussed quickly Wednesday evening

**Comment by gjn** [comment]
When will this be in production?

This is important to have reasonable settings for performance analysis.

Also, for WMTS tiles, we put `public, max-age=1800`. I propose we use the same for vector tiles. We had strange effects in clients when we had longer time for wmts tiles.

Note: this is NOT for Cloudfront, where we can cache longer if we want to (and invalidate on deploy)

**Comment by ltkum** [comment]
Changed the max age to 1800 and deployed on dev again. Seems to work. As soon as the PR is merged, I'll create the PR to deploy it to dev, int and prod. (I asked @swissmap for int, and said we can apply modifications to int).

**Comment by ltkum** [comment]
@danduk82 , @gjn 
It is now on dev, int and prod, and deploy from the master branch of the project deployer will use them. I'm closing the issue.
